<testsuite name="test_improved.WebAuthn Registration Test" tests="2" errors="2" failures="0" skipped="0" time="2.009021" timestamp="2025-07-14T15:11:47.777248" hostname="LAP-BE-DOCKXBE1"><testcase classname="test_improved.WebAuthn Registration Test" name="Registration with improved timing" status="failed" time="1.128069"><error type="NoSuchContextException" message="Message: No such context found.&#10;Stacktrace:&#10;NoSuchContextError: No such context found.&#10;    at AndroidUiautomator2Driver.setContext (C:\Users\x_dockxbe1\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:66:11)">
<![CDATA[
Failing step: Given I enter username "timing_test" ... failed in 0.775s
Location: features/test_improved.feature:10
Traceback (most recent call last):
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\webauthn_steps.py", line 42, in step_enter_username
    context.wa_util.fill_username(username=username)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\webauthn\webauthn_util.py", line 18, in fill_username
    self.controller.find_element(WebAuthnLocators.USERNAME_BOX).send_keys(username)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\shared\appium_util.py", line 55, in find_element
    self.switch_context(locator.context)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\shared\appium_util.py", line 50, in switch_context
    self.driver.switch_to.context(context.value)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\appium\webdriver\switch_to.py", line 40, in context
    self._driver.execute(MobileCommand.SWITCH_TO_CONTEXT, {'name': context_name})
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 454, in execute
    self.error_handler.check_response(response)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\appium\webdriver\errorhandler.py", line 125, in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
appium.common.exceptions.NoSuchContextException: Message: No such context found.
Stacktrace:
NoSuchContextError: No such context found.
    at AndroidUiautomator2Driver.setContext (C:\Users\x_dockxbe1\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:66:11)

Captured logging:
INFO     builtins: DIGIPASS FX7 device verified as connected
INFO     builtins: Navigating to WebAuthn registration page
INFO     builtins: Entering username: timing_test]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @hardware @registration @improved
  Scenario: Registration with improved timing
    Given I have a DIGIPASS FX7 device connected ... passed in 0.001s
    And I am on the WebAuthn registration page ... passed in 0.352s
    Given I enter username "timing_test" ... failed in 0.775s
    When I click the register button ... skipped in 0.000s
    And I complete the hardware registration flow ... skipped in 0.000s
    Then the registration should succeed ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="test_improved.WebAuthn Registration Test" name="Authentication with improved timing" status="failed" time="0.880951"><error type="NoSuchContextException" message="Message: No such context found.&#10;Stacktrace:&#10;NoSuchContextError: No such context found.&#10;    at AndroidUiautomator2Driver.setContext (C:\Users\x_dockxbe1\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:66:11)">
<![CDATA[
Failing step: Given I enter username "timing_test" ... failed in 0.523s
Location: features/test_improved.feature:17
Traceback (most recent call last):
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\webauthn_steps.py", line 42, in step_enter_username
    context.wa_util.fill_username(username=username)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\webauthn\webauthn_util.py", line 18, in fill_username
    self.controller.find_element(WebAuthnLocators.USERNAME_BOX).send_keys(username)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\shared\appium_util.py", line 55, in find_element
    self.switch_context(locator.context)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\shared\appium_util.py", line 50, in switch_context
    self.driver.switch_to.context(context.value)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\appium\webdriver\switch_to.py", line 40, in context
    self._driver.execute(MobileCommand.SWITCH_TO_CONTEXT, {'name': context_name})
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 454, in execute
    self.error_handler.check_response(response)
  File "C:\Users\x_dockxbe1\Downloads\mobiletests\mobiletests-master\.venv\Lib\site-packages\appium\webdriver\errorhandler.py", line 125, in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
appium.common.exceptions.NoSuchContextException: Message: No such context found.
Stacktrace:
NoSuchContextError: No such context found.
    at AndroidUiautomator2Driver.setContext (C:\Users\x_dockxbe1\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:66:11)

Captured logging:
INFO     builtins: DIGIPASS FX7 device verified as connected
INFO     builtins: Navigating to WebAuthn registration page
INFO     builtins: Entering username: timing_test]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @hardware @authentication @improved
  Scenario: Authentication with improved timing
    Given I have a DIGIPASS FX7 device connected ... passed in 0.000s
    And I am on the WebAuthn registration page ... passed in 0.358s
    Given I enter username "timing_test" ... failed in 0.523s
    When I click the authenticate button ... skipped in 0.000s
    And I complete the hardware authentication flow ... skipped in 0.000s
    Then the authentication should succeed ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>